# WattWise app ProGuard / R8 rules.

# ------------------------- Retrofit 2 -------------------------
# Retrofit uses reflection over @GET/@POST annotated interfaces.
-keepattributes Signature, InnerClasses, EnclosingMethod, *Annotation*
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
-keep,allowobfuscation,allowshrinking interface retrofit2.Call

# Keep generic signatures of Retrofit return types (Call<List<T>> flattening).
-if interface * { @retrofit2.http.* public *** *(...); }
-keep,allowoptimization,allowshrinking,allowobfuscation class <3>

# ------------------------- Gson -------------------------
# DTOs are serialized/deserialized by Gson through reflection.
-keep class com.wattwise.android.data.remote.dto.** { *; }
-keepattributes Signature
-keepattributes *Annotation*

# ------------------------- Room -------------------------
# Room generates code at compile time; the entities / DAOs are referenced by
# the generated implementation, but keep their members for SQL binding.
-keep class com.wattwise.android.data.local.entity.** { *; }
-keep class androidx.room.** { *; }

# ------------------------- OkHttp -------------------------
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**

# ------------------------- General trunk slimming -------------------------
-dontwarn org.codehaus.mojo.animal_sniffer.**

# Keep enum switch maps generated by the compiler.
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# WorkManager already bundles compatible consumer rules; nothing extra needed.